/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_recordModify} from './IReceivedDataAtServer_recordModify';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_recordModify};
export const IReceivedDataAtServer_recordModifySchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "IGameSystemEnvironment": {
      "defaultProperties": [
      ],
      "properties": {
        "gameDifficultyID": {
          "type": "string"
        },
        "gameModeID": {
          "type": "string"
        },
        "gameSystemID": {
          "type": "string"
        }
      },
      "required": [
        "gameDifficultyID",
        "gameModeID",
        "gameSystemID"
      ],
      "type": "object"
    },
    "IRecord": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "languageOfTagName": {
          "$ref": "#/definitions/LanguageInApplication"
        },
        "link": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "modifiedBy": {
          "items": {
            "$ref": "#/definitions/ModifiedHistoryStack"
          },
          "type": "array"
        },
        "note": {
          "type": "string"
        },
        "regulation": {
          "$ref": "#/definitions/IRegulation"
        },
        "runnerID": {
          "type": "string"
        },
        "score": {
          "type": "number"
        },
        "tagID": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tagName": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "timestamp_post": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "languageOfTagName",
        "link",
        "note",
        "regulation",
        "runnerID",
        "score",
        "tagID",
        "tagName",
        "timestamp_post"
      ],
      "type": "object"
    },
    "IRegulation": {
      "defaultProperties": [
      ],
      "properties": {
        "abilityIDs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "gameSystemEnvironment": {
          "$ref": "#/definitions/IGameSystemEnvironment"
        },
        "targetID": {
          "type": "string"
        }
      },
      "required": [
        "abilityIDs",
        "gameSystemEnvironment",
        "targetID"
      ],
      "type": "object"
    },
    "LanguageInApplication": {
      "enum": [
        "English",
        "Japanese"
      ],
      "type": "string"
    },
    "ModifiedHistoryStack": {
      "defaultProperties": [
      ],
      "properties": {
        "before": {
          "defaultProperties": [
          ],
          "properties": {
            "languageOfTagName": {
              "$ref": "#/definitions/LanguageInApplication"
            },
            "link": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "note": {
              "type": "string"
            },
            "regulation": {
              "$ref": "#/definitions/IRegulation"
            },
            "runnerID": {
              "type": "string"
            },
            "score": {
              "type": "number"
            },
            "tagID": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "tagName": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "timestamp_approval": {
              "type": "number"
            },
            "timestamp_post": {
              "type": "number"
            }
          },
          "required": [
            "languageOfTagName",
            "link",
            "note",
            "regulation",
            "runnerID",
            "score",
            "tagID",
            "tagName",
            "timestamp_post"
          ],
          "type": "object"
        },
        "modifierID": {
          "type": "string"
        },
        "timestamp": {
          "type": "number"
        }
      },
      "required": [
        "before",
        "modifierID",
        "timestamp"
      ],
      "type": "object"
    }
  },
  "properties": {
    "IDToken": {
      "$ref": "#/definitions/LanguageInApplication"
    },
    "language": {
      "$ref": "#/definitions/LanguageInApplication"
    },
    "record": {
      "$ref": "#/definitions/IRecord"
    },
    "recordID": {
      "type": "string"
    }
  },
  "required": [
    "IDToken",
    "language",
    "record",
    "recordID"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_recordModify = ajv.compile(IReceivedDataAtServer_recordModifySchema) as ValidateFunction<IReceivedDataAtServer_recordModify>;
export default function validate(value: unknown): IReceivedDataAtServer_recordModify {
  if (isIReceivedDataAtServer_recordModify(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_recordModify.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_recordModify'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
