/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_recordDelete} from './IReceivedDataAtServer_recordDelete';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":false});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_recordDelete};
export const IReceivedDataAtServer_recordDeleteSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "IDToken": {
      "type": "string"
    },
    "gameSystemEnv": {
      "properties": {
        "gameModeID": {
          "type": "string"
        },
        "gameSystemID": {
          "type": "string"
        }
      },
      "required": [
        "gameModeID",
        "gameSystemID"
      ],
      "type": "object"
    },
    "reason": {
      "type": "string"
    },
    "recordID": {
      "type": "string"
    }
  },
  "required": [
    "IDToken",
    "gameSystemEnv",
    "recordID"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_recordDelete = ajv.compile(IReceivedDataAtServer_recordDeleteSchema) as ValidateFunction<IReceivedDataAtServer_recordDelete>;
export default function validate(value: unknown): IReceivedDataAtServer_recordDelete {
  if (isIReceivedDataAtServer_recordDelete(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_recordDelete.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_recordDelete'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
