/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_recordModerate} from './IReceivedDataAtServer_recordModerate';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"useDefaults":false});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_recordModerate};
export const IReceivedDataAtServer_recordModerateSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "IDToken": {
      "type": "string"
    },
    "gameSystemEnv": {
      "properties": {
        "gameModeID": {
          "type": "string"
        },
        "gameSystemID": {
          "type": "string"
        }
      },
      "required": [
        "gameModeID",
        "gameSystemID"
      ],
      "type": "object"
    },
    "recordId": {
      "type": "string"
    }
  },
  "required": [
    "IDToken",
    "gameSystemEnv",
    "recordId"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_recordModerate = ajv.compile(IReceivedDataAtServer_recordModerateSchema) as ValidateFunction<IReceivedDataAtServer_recordModerate>;
export default function validate(value: unknown): IReceivedDataAtServer_recordModerate {
  if (isIReceivedDataAtServer_recordModerate(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_recordModerate.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_recordModerate'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
