/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_gameRule_get} from './IReceivedDataAtServer_gameRule_get';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"useDefaults":false});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_gameRule_get};
export const IReceivedDataAtServer_gameRule_getSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "LanguageInApplication": {
      "enum": [
        "English",
        "Japanese"
      ],
      "type": "string"
    }
  },
  "properties": {
    "gameSystemEnv": {
      "properties": {
        "gameModeID": {
          "type": "string"
        },
        "gameSystemID": {
          "type": "string"
        }
      },
      "required": [
        "gameModeID",
        "gameSystemID"
      ],
      "type": "object"
    },
    "language": {
      "$ref": "#/definitions/LanguageInApplication"
    },
    "targetRuleID": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "gameSystemEnv",
    "language"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_gameRule_get = ajv.compile(IReceivedDataAtServer_gameRule_getSchema) as ValidateFunction<IReceivedDataAtServer_gameRule_get>;
export default function validate(value: unknown): IReceivedDataAtServer_gameRule_get {
  if (isIReceivedDataAtServer_gameRule_get(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_gameRule_get.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_gameRule_get'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
