/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_getlist_UseId} from './IReceivedDataAtServer_getlist_UseId';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":false});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_getlist_UseId};
export const IReceivedDataAtServer_getlist_UseIdSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "id": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "limit": {
      "type": "number"
    },
    "start": {
      "type": "number"
    }
  },
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_getlist_UseId = ajv.compile(IReceivedDataAtServer_getlist_UseIdSchema) as ValidateFunction<IReceivedDataAtServer_getlist_UseId>;
export default function validate(value: unknown): IReceivedDataAtServer_getlist_UseId {
  if (isIReceivedDataAtServer_getlist_UseId(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_getlist_UseId.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_getlist_UseId'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
