/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_recordSearch} from './IReceivedDataAtServer_recordSearch';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_recordSearch};
export const IReceivedDataAtServer_recordSearchSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "IGameSystemEnvironment": {
      "defaultProperties": [
      ],
      "properties": {
        "gameDifficultyID": {
          "type": "string"
        },
        "gameModeID": {
          "type": "string"
        },
        "gameSystemID": {
          "type": "string"
        }
      },
      "required": [
        "gameDifficultyID",
        "gameModeID",
        "gameSystemID"
      ],
      "type": "object"
    },
    "IRecord": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "languageOfTagName": {
          "$ref": "#/definitions/LanguageInApplication"
        },
        "link": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "modifiedBy": {
          "items": {
            "$ref": "#/definitions/ModifiedHistoryStack"
          },
          "type": "array"
        },
        "note": {
          "type": "string"
        },
        "regulation": {
          "$ref": "#/definitions/IRegulation"
        },
        "runnerID": {
          "type": "string"
        },
        "score": {
          "type": "number"
        },
        "tagID": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tagName": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "timestamp_post": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "languageOfTagName",
        "link",
        "note",
        "regulation",
        "runnerID",
        "score",
        "tagID",
        "tagName",
        "timestamp_post"
      ],
      "type": "object"
    },
    "IRegulation": {
      "defaultProperties": [
      ],
      "properties": {
        "abilityIDs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "gameSystemEnvironment": {
          "$ref": "#/definitions/IGameSystemEnvironment"
        },
        "targetID": {
          "type": "string"
        }
      },
      "required": [
        "abilityIDs",
        "gameSystemEnvironment",
        "targetID"
      ],
      "type": "object"
    },
    "ISentRecordOffer": {
      "defaultProperties": [
      ],
      "properties": {
        "languageOfTagName": {
          "$ref": "#/definitions/LanguageInApplication"
        },
        "link": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "note": {
          "type": "string"
        },
        "regulation": {
          "$ref": "#/definitions/IRegulation"
        },
        "score": {
          "type": "number"
        },
        "tagName": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "languageOfTagName",
        "link",
        "note",
        "regulation",
        "score",
        "tagName"
      ],
      "type": "object"
    },
    "LanguageInApplication": {
      "enum": [
        "English",
        "Japanese"
      ],
      "type": "string"
    },
    "ModifiedHistoryStack": {
      "defaultProperties": [
      ],
      "properties": {
        "before": {
          "defaultProperties": [
          ],
          "properties": {
            "languageOfTagName": {
              "$ref": "#/definitions/LanguageInApplication"
            },
            "link": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "note": {
              "type": "string"
            },
            "regulation": {
              "$ref": "#/definitions/IRegulation"
            },
            "runnerID": {
              "type": "string"
            },
            "score": {
              "type": "number"
            },
            "tagID": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "tagName": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "timestamp_approval": {
              "type": "number"
            },
            "timestamp_post": {
              "type": "number"
            }
          },
          "required": [
            "languageOfTagName",
            "link",
            "note",
            "regulation",
            "runnerID",
            "score",
            "tagID",
            "tagName",
            "timestamp_post"
          ],
          "type": "object"
        },
        "modifierID": {
          "type": "string"
        },
        "timestamp": {
          "type": "number"
        }
      },
      "required": [
        "before",
        "modifierID",
        "timestamp"
      ],
      "type": "object"
    },
    "OrderOfRecordArray": {
      "enum": [
        "EarlierFirst",
        "HigherFirst",
        "LaterFirst",
        "LowerFirst"
      ],
      "type": "string"
    },
    "SearchCondition": {
      "defaultProperties": [
      ],
      "properties": {
        "abilityIDs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "abilityIDsCondition": {
          "description": "能力カテゴリを用いた記録検索において、And検索を行うかOr検索を行うか",
          "enum": [
            "AND",
            "AllowForOrder",
            "OR"
          ],
          "type": "string"
        },
        "gameSystemEnv": {
          "defaultProperties": [
          ],
          "properties": {
            "gameDifficultyID": {
              "description": "//#NOTE これによる指定は、targetIDsによるものよりも強い指定となる",
              "type": "string"
            },
            "gameModeID": {
              "type": "string"
            },
            "gameSystemID": {
              "type": "string"
            }
          },
          "required": [
            "gameModeID",
            "gameSystemID"
          ],
          "type": "object"
        },
        "groupName": {
          "type": "string"
        },
        "groupSubName": {
          "type": "string"
        },
        "language": {
          "$ref": "#/definitions/LanguageInApplication"
        },
        "limitOfRecordArray": {
          "type": "number"
        },
        "orderOfRecordArray": {
          "$ref": "#/definitions/OrderOfRecordArray"
        },
        "runnerIDs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "startOfRecordArray": {
          "type": "number"
        },
        "tagIDs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "targetIDs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "gameSystemEnv",
        "groupName",
        "language",
        "orderOfRecordArray"
      ],
      "type": "object"
    }
  },
  "properties": {
    "condition": {
      "items": {
        "$ref": "#/definitions/SearchCondition"
      },
      "type": "array"
    }
  },
  "required": [
    "condition"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_recordSearch = ajv.compile(IReceivedDataAtServer_recordSearchSchema) as ValidateFunction<IReceivedDataAtServer_recordSearch>;
export default function validate(value: unknown): IReceivedDataAtServer_recordSearch {
  if (isIReceivedDataAtServer_recordSearch(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_recordSearch.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_recordSearch'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
