/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IReceivedDataAtServer_pickUp_UseId} from './IReceivedDataAtServer_pickUp_UseId';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IReceivedDataAtServer_pickUp_UseId};
export const IReceivedDataAtServer_pickUp_UseIdSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIReceivedDataAtServer_pickUp_UseId = ajv.compile(IReceivedDataAtServer_pickUp_UseIdSchema) as ValidateFunction<IReceivedDataAtServer_pickUp_UseId>;
export default function validate(value: unknown): IReceivedDataAtServer_pickUp_UseId {
  if (isIReceivedDataAtServer_pickUp_UseId(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIReceivedDataAtServer_pickUp_UseId.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IReceivedDataAtServer_pickUp_UseId'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
